### ISSUE TITLE
OpenGlApplication not working

### ISSUE THREAD

**Issue by haraldsteinlechner** [haraldsteinlechner/aardvark-notebook-demo#1]
native dependency loading problem in ultz glfw. might be fixed in current version - check 5.1

**Comment by haraldsteinlechner** [comment]
```
Error: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.DotNet.PlatformAbstractions, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.
File name: 'Microsoft.DotNet.PlatformAbstractions, Version=3.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
at Ultz.SuperInvoke.Loader.DefaultPathResolver.TryLocateNativeAssetFromDeps(String name, String& appLocalNativePath, String& depsResolvedPath)
at Ultz.SuperInvoke.Loader.DefaultPathResolver.EnumeratePossibleLibraryLoadTargets(String name)+MoveNext()
at Ultz.SuperInvoke.Loader.LibraryLoader.LoadWithResolver(String name, PathResolver pathResolver)
at Ultz.SuperInvoke.Loader.LibraryLoader.TryLoadNativeLibrary(String[] names, PathResolver pathResolver, IntPtr& result)
at Ultz.SuperInvoke.Loader.LibraryLoader.TryLoadNativeLibrary(String name, PathResolver pathResolver, IntPtr& result)
a
```
